apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
  - name: GlitchTip
    uid: glitchtip
    type: marcusolsson-json-datasource
    access: proxy
    url: http://glitchtip:8000
    editable: true
